# Generated by Django 5.0.2 on 2024-02-15 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="товар")),
                (
                    "product_model",
                    models.CharField(max_length=255, verbose_name="модель"),
                ),
                (
                    "launch_date",
                    models.DateField(verbose_name="дата выхода товара на рынок"),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                ("city", models.CharField(max_length=200, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                ("house", models.CharField(max_length=100, verbose_name="Номер дома")),
                (
                    "network_level",
                    models.IntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        verbose_name="Уровень структуры",
                    ),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Задолженность",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор поставщика",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        to="electronics.product", verbose_name="Продукт"
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electronics.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "поставщик",
                "verbose_name_plural": "поставщики",
            },
        ),
    ]
